name: strongroom
description: Personal high-security vault
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cryptography: ^2.7.0
  cryptography_flutter: ^2.3.2
  flutter_secure_storage: ^9.2.2
flutter:
  uses-material-design: true
